apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  NEXT_PUBLIC_API_BASE_URL: https://api.iskolelk.com/api/v1
  NEXT_PUBLIC_API_BASE_URL_FILES: https://api.iskolelk.com
  NEXT_PUBLIC_SITE_URL: https://iskolelk.com
  # NEXT_PUBLIC_API_BASE_URL: http://backend-service:3002/api/v1
  # NEXT_PUBLIC_API_BASE_URL_FILES: http://backend-service:3002
  # NEXT_PUBLIC_SITE_URL: http://localhost:3000 # TODO: change to the actual volume claim name
